import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "./context/UserContext"; // already client component

export const metadata: Metadata = {
  title: "Kumulli Bachchu Mia Model High School",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Client component wrap করা হয়েছে */}
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
